### ISSUE TITLE
Invalid heap heap size

### ISSUE THREAD

**Issue by flloschy** [SimplicityGuy/docker-minecraft-skyfactory4#1]
Hi!
Im trying to setup this container with the following docker-compose file 
```yml
version: "3"
services:
    minecraft-skyfactory4:
        stdin_open: true
        tty: true
        ports:
            - 25565:25565
        environment:
            - EULA=TRUE
        volumes:
            - ./data:/data
        container_name: mcs-sf
        image: ghcr.io/simplicityguy/minecraft-skyfactory4
```
and the container starts but java throws this error: `Invalid initial heap size: -Xms4048m -Xmx4048` 
I've tried to overwrite this by adding a environment variable `JVM_OPTS=-Xmx8096m -Xms256m` and did various combinations of order, `m`/`M` and memory size but the error is always the same... 

Ive of course also tried using the docker command you have provided `docker run -dit -p 25565:25565 -e EULA=TRUE -v ~/minecraft/data:/data --name mcs-sf ghcr.io/simplicityguy/minecraft-skyfactory4` but same issue

Do you have an idea on what i'm doing wrong? Or did something change and this image doesn't work anymore or is outdated anyway?
